
const $=id=>document.getElementById(id);const storeKey='civiqueFoyerLuzelV2';let state=JSON.parse(localStorage.getItem(storeKey)||'{}');state={done:0,good:0,wrong:{},fav:{},sessions:[],settings:{font:18,dark:false,contrast:false,voice:false},...state};let current=[],idx=0,score=0,answered=false,mode='train',flash=0,timer=null,startTime=0,seconds=0;
function save(){localStorage.setItem(storeKey,JSON.stringify(state));stats()}function show(id){document.querySelectorAll('main>section').forEach(s=>s.classList.add('hidden'));$(id).classList.remove('hidden');window.scrollTo(0,0)}function init(){applySettings();fillThemes();stats();renderHomeThemes(); if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');}
function applySettings(){document.documentElement.style.fontSize=(state.settings.font||18)+'px';document.body.classList.toggle('dark',!!state.settings.dark);document.body.classList.toggle('contrast',!!state.settings.contrast);$('fontSize').value=state.settings.font||18;$('voiceAuto').checked=!!state.settings.voice}
function setFont(v){state.settings.font=Number(v);save();applySettings()}function toggleDark(){state.settings.dark=!state.settings.dark;save();applySettings()}function toggleContrast(){state.settings.contrast=!state.settings.contrast;save();applySettings()}function toggleVoice(){state.settings.voice=$('voiceAuto').checked;save()}function themes(){return [...new Map(QUESTIONS.map(q=>[q.themeId,q.theme])).entries()].map(([id,name])=>({id,name,count:QUESTIONS.filter(q=>q.themeId===id).length}))}
function fillThemes(){let opts=['<option value="all">Tous les thèmes</option>',...themes().map(t=>`<option value="${t.id}">${t.name} (${t.count})</option>`)].join('');$('theme').innerHTML=opts;$('searchTheme').innerHTML=opts}
function renderHomeThemes(){$('themeTiles').innerHTML=themes().map(t=>`<div class="tile" onclick="quickTheme('${t.id}')"><b>${t.name}</b><span class="muted">${t.count} questions disponibles</span></div>`).join('')}
function stats(){let rate=state.done?Math.round(state.good/state.done*100):0;$('sDone').textContent=state.done;$('sRate').textContent=rate+' %';$('sWeak').textContent=Object.keys(state.wrong).length;$('sFav').textContent=Object.values(state.fav).filter(Boolean).length;$('globalBar').style.width=Math.min(100,state.done/QUESTIONS.length*100)+'%';}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function setup(m='train'){mode=m;show('setup');$('setupTitle').textContent=m==='exam'?'Préparer un examen blanc':'Préparer un entraînement';$('count').value=m==='exam'?'40':'10';$('examInfo').classList.toggle('hidden',m!=='exam')}
function quickTheme(id){setup('train');$('theme').value=id;startQuiz()}function startQuiz(custom){let th=$('theme').value;let cnt=$('count').value;let source=custom||QUESTIONS.filter(q=>th==='all'||q.themeId===th);current=shuffle(source);if(cnt!=='all')current=current.slice(0,Math.min(Number(cnt),current.length));if(mode==='exam')current=shuffle(QUESTIONS).slice(0,Math.min(40,QUESTIONS.length));idx=0;score=0;seconds=0;startTime=Date.now();clearInterval(timer);timer=setInterval(()=>{seconds=Math.floor((Date.now()-startTime)/1000);$('timer').textContent=formatTime(seconds)},1000);show('quiz');renderQ()}
function formatTime(s){let m=Math.floor(s/60),r=s%60;return `${m}:${String(r).padStart(2,'0')}`}function renderQ(){answered=false;let q=current[idx];$('qTheme').textContent=q.theme;$('qPos').textContent=`${idx+1}/${current.length}`;$('qScore').textContent=`Score ${score}`;$('quizBar').style.width=(idx/current.length*100)+'%';$('qText').textContent=q.question;$('favBtn').textContent=state.fav[q.id]?'★ Favori':'☆ Favori';$('options').innerHTML=q.options.map((o,i)=>`<button class="option" onclick="choose(${i})"><strong>${String.fromCharCode(65+i)}.</strong> ${escapeHTML(o)}</button>`).join('');$('feedback').classList.add('hidden');$('next').textContent=idx===current.length-1?'Terminer':'Question suivante';if(state.settings.voice)speakQuestion()}
function escapeHTML(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function choose(i){if(answered)return;answered=true;let q=current[idx],ok=i===q.answer;document.querySelectorAll('.option').forEach((b,n)=>{if(n===q.answer)b.classList.add('correct');if(n===i&&!ok)b.classList.add('wrong')});if(ok){score++;state.good++}else{state.wrong[q.id]=(state.wrong[q.id]||0)+1}state.done++;save();$('feedback').classList.remove('hidden');$('feedback').innerHTML=`<h3>${ok?'✅ Bonne réponse':'❌ Réponse incorrecte'}</h3><p><strong>Bonne réponse :</strong> ${escapeHTML(q.options[q.answer])}</p><p>${escapeHTML(q.explanation)}</p>`;if(state.settings.voice)speak((ok?'Bonne réponse. ':'Réponse incorrecte. ')+q.explanation)}
function nextQ(){if(!answered){alert('Sélectionnez une réponse pour continuer.');return} if(idx<current.length-1){idx++;renderQ()}else finish()}function finish(){clearInterval(timer);let rate=Math.round(score/current.length*100);state.sessions.push({date:new Date().toLocaleString('fr-FR'),mode:mode==='exam'?'Examen blanc':'Entraînement',score,total:current.length,rate,time:formatTime(seconds)});save();show('result');$('resScore').textContent=`${score}/${current.length} — ${rate} %`;$('resMsg').textContent=rate>=80?'Objectif atteint : très bon résultat.':'Objectif non atteint pour le moment : les erreurs sont automatiquement ajoutées aux révisions.';$('resTime').textContent='Temps : '+formatTime(seconds)}
function toggleFav(){let q=current[idx];state.fav[q.id]=!state.fav[q.id];save();$('favBtn').textContent=state.fav[q.id]?'★ Favori':'☆ Favori'}function revision(){show('revision');let ids=new Set([...Object.keys(state.wrong),...Object.keys(state.fav).filter(k=>state.fav[k])]);let list=QUESTIONS.filter(q=>ids.has(String(q.id)));$('revCount').textContent=list.length;$('revList').innerHTML=list.length?list.map(q=>`<div class="searchItem"><b>${q.theme}</b><p>${escapeHTML(q.question)}</p><p class="muted">${escapeHTML(q.explanation)}</p></div>`).join(''):'<p class="muted">Aucune question à retravailler pour le moment.</p>'}
function startRevision(){let ids=new Set([...Object.keys(state.wrong),...Object.keys(state.fav).filter(k=>state.fav[k])]);let list=QUESTIONS.filter(q=>ids.has(String(q.id)));if(!list.length){alert('Aucune question ciblée pour le moment.');return}mode='revision';startQuiz(list)}
function search(){show('search');renderSearch()}function renderSearch(){let txt=$('searchBox').value?.toLowerCase()||'',th=$('searchTheme').value;let list=QUESTIONS.filter(q=>(th==='all'||q.themeId===th)&&((q.question+' '+q.options.join(' ')+' '+q.explanation).toLowerCase().includes(txt)));$('searchResults').innerHTML=list.slice(0,80).map(q=>`<div class="searchItem"><b>${q.theme}</b><p>${escapeHTML(q.question)}</p><p class="muted">Réponse : ${escapeHTML(q.options[q.answer])}</p></div>`).join('')||'<p class="muted">Aucun résultat.</p>'}
const cards=[['Liberté','Pouvoir agir, penser, croire et s’exprimer dans le respect de la loi.'],['Égalité','Même traitement devant la loi, lutte contre les discriminations.'],['Fraternité','Solidarité, entraide et cohésion sociale.'],['Laïcité','Liberté de conscience et neutralité de l’État.'],['Marianne','Figure féminine représentant la République.'],['Président de la République','Élu pour 5 ans, nomme le Premier ministre, chef des armées.'],['Parlement','Assemblée nationale et Sénat : vote les lois et contrôle le Gouvernement.'],['Sécurité sociale','Protège face aux risques de la vie : santé, famille, retraite.'],['JDC','Journée Défense et Citoyenneté.'],['Union européenne','Organisation d’États européens dont la France est membre.']];function flashcards(){show('flash');flash=0;renderFlash()}function renderFlash(){let c=cards[flash];$('flashCard').innerHTML=`<h3>${c[0]}</h3><p>${c[1]}</p><p class="muted">${flash+1}/${cards.length}</p>`}function nextFlash(){flash=(flash+1)%cards.length;renderFlash()}function prevFlash(){flash=(flash-1+cards.length)%cards.length;renderFlash()}
function dashboard(){show('dashboard');let sessions=state.sessions.slice(-12).reverse();$('sessions').innerHTML=sessions.length?sessions.map(s=>`<div class="searchItem"><b>${s.date}</b><p>${s.mode} — ${s.score}/${s.total} — ${s.rate}% — ${s.time}</p></div>`).join(''):'<p class="muted">Aucune session enregistrée.</p>';makeReport()}function makeReport(){let rate=state.done?Math.round(state.good/state.done*100):0;let weak=Object.keys(state.wrong).map(id=>QUESTIONS.find(q=>q.id==id)).filter(Boolean).slice(0,10);$('report').textContent=`Bilan Examen civique — Foyer Luzel\nDate : ${new Date().toLocaleDateString('fr-FR')}\n\nQuestions réalisées : ${state.done}\nTaux de réussite global : ${rate}%\nQuestions à retravailler : ${Object.keys(state.wrong).length}\nFavoris : ${Object.values(state.fav).filter(Boolean).length}\n\nPrincipaux points à retravailler :\n${weak.map(q=>'- '+q.theme+' : '+q.question).join('\n')||'Aucun pour le moment.'}`}
function exportCSV(){let lines=['date;mode;score;total;taux;temps',...state.sessions.map(s=>`${s.date};${s.mode};${s.score};${s.total};${s.rate};${s.time}`)];download('bilan_examen_civique.csv',lines.join('\n'),'text/csv')}function exportJSON(){download('sauvegarde_examen_civique.json',JSON.stringify(state,null,2),'application/json')}function download(name,content,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click()}function printReport(){window.print()}function resetData(){if(confirm('Effacer tous les résultats et réglages ?')){localStorage.removeItem(storeKey);location.reload()}}
function speak(t){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='fr-FR';speechSynthesis.speak(u)}function speakQuestion(){let q=current[idx];if(q)speak(q.question+'. '+q.options.map((o,i)=>String.fromCharCode(65+i)+'. '+o).join('. '));else speak('Application d entraînement à l examen civique.')}window.addEventListener('load',init);
